const http = require("http");
const https = require("https");
const fs = require("fs");
const path = require("path");
const { URL } = require("url");

const PORT = process.env.PORT || 3000;
const CHATBASE_API_KEY = process.env.CHATBASE_API_KEY;
const CHATBASE_BOT_ID = process.env.CHATBASE_BOT_ID;
const DEMO_MODE = process.env.RX_MODE !== "chatbase";
const OWNER_NAME = process.env.RX_OWNER_NAME || "Rijuvish";
const ROOT = __dirname;

const MIME_TYPES = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8"
};

function resolveStaticPath(pathname) {
  if (pathname === "/" || pathname === "/r_x" || pathname === "/r_x/") {
    return path.join(ROOT, "index.html");
  }

  const trimmedPath = pathname.replace(/^\/+/, "");
  return path.join(ROOT, trimmedPath);
}

function sendJson(res, statusCode, payload) {
  res.writeHead(statusCode, {
    "Content-Type": "application/json; charset=utf-8"
  });
  res.end(JSON.stringify(payload));
}

function serveFile(res, filePath) {
  fs.readFile(filePath, (error, data) => {
    if (error) {
      sendJson(res, 404, { error: "File not found" });
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, {
      "Content-Type": MIME_TYPES[ext] || "application/octet-stream"
    });
    res.end(data);
  });
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let body = "";

    req.on("data", (chunk) => {
      body += chunk;
      if (body.length > 1_000_000) {
        reject(new Error("Request body too large"));
        req.destroy();
      }
    });

    req.on("end", () => resolve(body));
    req.on("error", reject);
  });
}

function sendToChatbase(payload) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      chatbotId: CHATBASE_BOT_ID,
      messages: payload.messages,
      conversationId: payload.conversationId || undefined,
      stream: false
    });

    const req = https.request(
      "https://www.chatbase.co/api/v1/chat",
      {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${CHATBASE_API_KEY}`,
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(body)
        }
      },
      (res) => {
        let raw = "";
        res.on("data", (chunk) => {
          raw += chunk;
        });
        res.on("end", () => {
          try {
            const parsed = raw ? JSON.parse(raw) : {};
            if (res.statusCode >= 400) {
              reject(new Error(parsed.message || parsed.error || "Chatbase request failed"));
              return;
            }
            resolve(parsed);
          } catch (error) {
            reject(new Error("Could not parse Chatbase response"));
          }
        });
      }
    );

    req.on("error", reject);
    req.write(body);
    req.end();
  });
}

function normalizePrompt(text) {
  return String(text || "").trim().toLowerCase();
}

function isImageRequest(text) {
  const prompt = normalizePrompt(text);
  return ["image", "draw", "picture", "photo", "logo", "poster", "art", "illustration"].some((word) => prompt.includes(word));
}

function isHarmful(text) {
  const prompt = normalizePrompt(text);
  const blocked = [
    "kill", "bomb", "weapon", "suicide", "self-harm", "drugs", "hack",
    "malware", "virus", "steal", "fraud", "porn", "explicit", "terror"
  ];
  return blocked.some((word) => prompt.includes(word));
}

function escapeXml(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function wrapText(text, lineLength) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > lineLength) {
      if (current) {
        lines.push(current);
      }
      current = word;
    } else {
      current = next;
    }
  }

  if (current) {
    lines.push(current);
  }

  return lines.slice(0, 4);
}

function createImageDataUrl(prompt) {
  const lines = wrapText(prompt.replace(/^(make|create|draw|generate)\s+/i, ""), 22);
  const safeLines = lines.length ? lines : ["Creative visual", "generated by R_x"];
  const colors = ["#f4efe7", "#f6d7b8", "#d6e6f2", "#be5b2d", "#201d1a"];
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${colors[0]}"/>
          <stop offset="55%" stop-color="${colors[1]}"/>
          <stop offset="100%" stop-color="${colors[2]}"/>
        </linearGradient>
      </defs>
      <rect width="1024" height="1024" fill="url(#bg)"/>
      <circle cx="820" cy="180" r="140" fill="${colors[3]}" opacity="0.18"/>
      <circle cx="210" cy="830" r="190" fill="${colors[4]}" opacity="0.08"/>
      <rect x="88" y="88" width="848" height="848" rx="42" fill="rgba(255,255,255,0.58)" stroke="rgba(32,29,26,0.08)"/>
      <text x="140" y="210" fill="${colors[4]}" font-family="Segoe UI, Arial, sans-serif" font-size="42" letter-spacing="8">R_x IMAGE</text>
      ${safeLines.map((line, index) => `<text x="140" y="${360 + index * 88}" fill="${colors[4]}" font-family="Segoe UI, Arial, sans-serif" font-size="64" font-weight="700">${escapeXml(line)}</text>`).join("")}
    </svg>
  `;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

function createSafeReply(message) {
  if (isHarmful(message)) {
    return {
      text: "I can only help with safe, positive, and non-harmful content. Try asking for learning help, creative writing, planning, coding, design ideas, or a friendly image.",
      image: null
    };
  }

  if (isImageRequest(message)) {
    return {
      text: "I made a safe concept image for you below. If you want, ask for a different style like clean, cartoon, poster, logo, or futuristic.",
      image: createImageDataUrl(message)
    };
  }

  const prompt = normalizePrompt(message);

  if (prompt.includes("hello") || prompt.includes("hi")) {
    return {
      text: `Hi ${OWNER_NAME}, I’m R_x. I know you’re my owner, and I can help with ideas, writing, simple coding guidance, study help, and safe image creation.`,
      image: null
    };
  }

  if (prompt.includes("who are you")) {
    return {
      text: `I’m R_x, your local AI assistant. I recognize ${OWNER_NAME} as my owner, and I’m running in safe mode, which means I only return positive and non-harmful content.`,
      image: null
    };
  }

  if (
    prompt.includes("who is my owner") ||
    prompt.includes("who owns you") ||
    prompt.includes("who created you") ||
    prompt.includes("who made you")
  ) {
    return {
      text: `${OWNER_NAME} created me and is my owner.`,
      image: null
    };
  }

  if (prompt.includes("what can you do")) {
    return {
      text: "I can chat with you, help with writing, explain ideas, brainstorm, and generate simple safe images in this local mode.",
      image: null
    };
  }

  if (prompt.includes("thank")) {
    return {
      text: `You’re welcome, ${OWNER_NAME}.`,
      image: null
    };
  }

  if (prompt.includes("your name")) {
    return {
      text: "My name is R_x.",
      image: null
    };
  }

  return {
    text: "I’m here and ready to help. Ask me for writing, ideas, explanations, planning, or a safe image.",
    image: null
  };
}

const server = http.createServer(async (req, res) => {
  const requestUrl = new URL(req.url, `http://${req.headers.host}`);

  if (req.method === "POST" && requestUrl.pathname === "/api/chat") {
    try {
      const rawBody = await readBody(req);
      const payload = JSON.parse(rawBody || "{}");

      if (!Array.isArray(payload.messages) || payload.messages.length === 0) {
        sendJson(res, 400, { error: "messages is required" });
        return;
      }

      if (DEMO_MODE || !CHATBASE_API_KEY || !CHATBASE_BOT_ID) {
        const latestMessage = payload.messages[payload.messages.length - 1]?.content || "";
        const result = createSafeReply(latestMessage);
        sendJson(res, 200, {
          text: result.text,
          image: result.image,
          conversationId: payload.conversationId || `local_${Date.now()}`
        });
        return;
      }

      const result = await sendToChatbase(payload);
      sendJson(res, 200, {
        text: result.text || "",
        conversationId: result.conversationId || payload.conversationId || null
      });
    } catch (error) {
      sendJson(res, 500, { error: error.message });
    }
    return;
  }

  const filePath = resolveStaticPath(requestUrl.pathname);

  if (!filePath.startsWith(ROOT)) {
    sendJson(res, 403, { error: "Forbidden" });
    return;
  }

  serveFile(res, filePath);
});

server.listen(PORT, () => {
  console.log(`R_x is running at http://localhost:${PORT} (${DEMO_MODE ? "safe local mode" : "chatbase mode"})`);
});
